remote_theme: chrisbobbe/jekyll-theme-prologue
# The following settings are NECESSARY for the Prologue theme to run:
theme:  jekyll-theme-prologue
collections: [sections]

title: Fun in Engineering
subtitle: Software Engineering and Making
description: >- # this means to ignore newlines until "baseurl:"
  This is the demo site for a Jekyll theme version of
  HTML5 UP's sleek, responsive site template Prologue.
author: Your Incredible Name
email: heronog@gmail.com
avatar: assets/images/avatar.jpg

# You'll want to customize url and baseurl for your own site:
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://beta.heronordonez.com" # the base hostname & protocol for your site

# Social settings
# Make sure to include the full url including protocol, e.g. https://github.com/chrisbobbe
twitter_url:
facebook_url:
googleplus_url:
instagram_url:
linkedin_url:
github_url:
pinterest_url:
slack_url:
dribbble_url:

# Google Analytics Tracking ID goes here:
google_analytics:
